[build]
publish = "flexpair.com/public"
command = "cd flexpair.com && hugo --minify --gc --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.101.0"
HUGO_THEME = "repo"
HUGO_BASEURL = "/"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[plugins]]
package = "netlify-plugin-visual-diff"

[plugins.inputs]
serverUrl = "https://eyesapi.applitools.com" # The public Eyes server
ignoreSelector = ".btn .social-links"
failBuildOnDiff = false
concurrency = 1

[[plugins.inputs.browser]]
name = "chrome"
width = 1024
height = 768
