#################### default parameters #######################################
# https://docs.gethugothemes.com/andromeda/basic-configuration/#default-parameters

# Place your favicon in the assets/images folder and put the path here.
favicon512 = "images/favicons/favicon512px.png"
favicon192 = "images/favicons/favicon192px.png"
favicon180 = "images/favicons/favicon180px.png"
favicon144 = "images/favicons/favicon144px.png"
favicon96 = "images/favicons/favicon96px.png"
favicon72 = "images/favicons/favicon72px.png"
favicon48 = "images/favicons/favicon48px.png"
favicon32 = "images/favicons/favicon32px.png"
favicon16 = "images/favicons/favicon16px.png"

# Place your logo in the assets/images folder and put the path here.
logo = "images/SyncopateBoldFlexPAIR.svg"

# Defines the width of the logo in pixels. It doesn’t work with .svg file.
# Use `x` with logo_width, example: "100x"
logo_width = "240x"

# logo text will only show when logo is missing.
logo_text = "Flexpair"

# image gallery shortcode
image_gallery = true

# footer information
footer_info = "The full spectrum of collaboration modes in one environment. For data science, DevOps and creative teams around the globe."

# As Hugo generates a static site, so you need to activate this form by a 
# third-party service. You can use any of Airform, https://formspree.io, or Formsubmit.
# Go to any of the sites that you preferred, and get your form action from there.
# Then, paste it here. If you use Airform, your form action will be like this: 
# https://airform.io/your@email.com.
contact_form_action = "https://formspree.io/f/xgernlzd"

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# mainSections defines the section names that you want to show on your website.
# It’s an array, so you can add more sections to show. For more information,
# see https://gohugo.io/functions/where/#mainsections.
mainSections= ["blog"]

# contact information showing in the footer and contact page
[contact_info]
address = "Bergheimerstr. 7, Heidelberg, Germany"
phone = ["+49-6221-7189618"]
email = ["flexpair@icloud.com"]
address_img = "images/address.png"
maps_link = "https://goo.gl/maps/ikqiZGc6SZQzxaeL7"

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader is for your website preloader, which means it will show up until 
# your website loads properly in the background. You can enable or disable 
# preloader by setting the value of enable as true or false. If you want to put
# any image, logo, or animation as your preloader, give the file location in 
# the preloader = , ex: preloader = images/preloader.gif. If you don’t want 
# any logo or image, leave the preloader field empty. So it will show just a
#  white screen when every component is loading.
[preloader]
enable = true
preloader = "images/favicons/loader.svg" # use svg

# Navigation button
[navigation_button]
enable = true
label = "Sign Up Now 🚀"
link = "signup/"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Hugo", "Themefisher", "GetHugoThemes"]


# Your default meta description. It shows on your homepage and other pages that
# have no meta description on this page front-matter.
description = "Software and SAAS Landing Hugo Theme"

# The website author name. It is used in the meta author tag.
author = "Jens F."

# image is used as the fallback for open graph and twitter card if a page has
# no image of its own.
image = "images/og-image.jpg"

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Your support is highly appreciated"
content = "Please help us to continuously improve Flexpair by making the donation you can afford."
button = "Buy us a coffee or ☕☕"
button_link = "https://www.buymeacoffee.com/flexpair"

############################# social networks #################################

# social is a loop item for your website’s social icons. You can add a loop 
# item by following the existing loop. We are using Line Awesome icon pack 
# for this theme. You can choose more icons from https://icons8.com/line-awesome
[[social]]
title = "LinkedIn"
icon = "lab la-linkedin-in"
link = "https://de.linkedin.com/in/fielenbach"

[[social]]
title = "GitHub"
icon = "lab la-github"
link = "https://github.com/jafudi"

[[social]]
title = "GitLab"
icon = "lab la-gitlab"
link = "https://gitlab.com/Jafudi"

