#################### default parameters ################################
# https://docs.gethugothemes.com/andromeda/basic-configuration/#default-parameters

# favicon
favicon512 = "images/favicons/favicon512px.png"
favicon192 = "images/favicons/favicon192px.png"
favicon180 = "images/favicons/favicon180px.png"
favicon144 = "images/favicons/favicon144px.png"
favicon96 = "images/favicons/favicon96px.png"
favicon72 = "images/favicons/favicon72px.png"
favicon48 = "images/favicons/favicon48px.png"
favicon32 = "images/favicons/favicon32px.png"
favicon16 = "images/favicons/favicon16px.png"

# logo
logo = "images/SyncopateBoldFlexPAIR.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Flexpair"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Jens F."
image = "images/SyncopateBoldFlexPAIR.svg" # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections= ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Heidelberg, Germany"
phone = ["+49-6221-7189618"]
email = ["flexpair@icloud.com", "jens@flexpair.com"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicons/loader.svg" # use svg

# Navigation button
[navigation_button]
enable = true
label = "Buy Premium 🚀"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Your support is highly appreciated"
content = "Please help us to continuously improve Flexpair by making the donation you can afford."
button = "Buy us a coffee or ☕☕"
button_link = "https://www.buymeacoffee.com/flexpair"

############################# social site ########################

[[social]]
title = "LinkedIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://de.linkedin.com/in/fielenbach"

[[social]]
title = "XING"
icon = "lab la-xing" # https://icons8.com/line-awesome
link = "https://www.xing.com/profile/Jens_FielenbachDiplMath/cv"

[[social]]
title = "Facebook"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://m.facebook.com/profile.php?id=100002090784709"
